FROM grey.ctf/evm-infra

COPY ./contracts /tmp/contracts

ENV PUBLIC_IP="block.nusgreyhats.org"
ENV FLAG="greyctf{learning_the_ropes!},greyctf{writing_my_first_fallback},greyctf{wrote_my_first_reentrancy_attack!}"
ENV PORT=8000
ENV HTTP_PORT=80
ENV CONTRACT_DEPLOY_VALUE=200
ENV PLAYER_VALUE=1
ENV RPC_KILL_TIMEOUT=7200
